image walk_to_school = "bg/walk_to_school/day.jpg"
image walk_to_school day = "bg/walk_to_school/day.jpg"
image walk_to_school day rain = "bg/walk_to_school/rain.jpg"
image walk_to_school evening = "bg/walk_to_school/evening.jpg"
image walk_to_school night dark = "bg/walk_to_school/night_dark.jpg"
image walk_to_school night dark rain = "bg/walk_to_school/night_dark_rain.jpg"
image walk_to_school night light = "bg/walk_to_school/night_light.jpg"
image walk_to_school night light rain = "bg/walk_to_school/night_light_rain.jpg"
image walk_to_school cloudy = "bg/walk_to_school/cloud.jpg"

image shops = "bg/shops/day.jpg"
image shops day = "bg/shops/day.jpg"
image shops day rain = "bg/shops/rain.jpg"
image shops evening = "bg/shops/evening.jpg"
image shops night dark = "bg/shops/night_dark.jpg"
image shops night dark rain = "bg/shops/night_dark_rain.jpg"
image shops night light = "bg/shops/night_light.jpg"
image shops night light rain = "bg/shops/night_light_rain.jpg"
image shops cloudy = "bg/shops/cloud.jpg"

image store = "bg/store/day.jpg"
image store day = "bg/store/day.jpg"
image store day rain = "bg/store/rain.jpg"
image store evening = "bg/store/evening.jpg"
image store night dark = "bg/store/night_dark.jpg"
image store night dark rain = "bg/store/night_dark_rain.jpg"
image store night light = "bg/store/night_light.jpg"
image store night light rain = "bg/store/night_light_rain.jpg"
image store cloudy = "bg/store/cloud.jpg"

image hardware_store = "bg/hardware_store/day.jpg"
image hardware_store day = "bg/hardware_store/day.jpg"
image hardware_store day rain = "bg/hardware_store/rain.jpg"
image hardware_store evening = "bg/hardware_store/evening.jpg"
image hardware_store night dark = "bg/hardware_store/night_dark.jpg"
image hardware_store night dark rain = "bg/hardware_store/night_dark_rain.jpg"
image hardware_store night light = "bg/hardware_store/night_light.jpg"
image hardware_store night light rain = "bg/hardware_store/night_light_rain.jpg"
image hardware_store cloudy = "bg/hardware_store/cloud.jpg"

image school = "bg/school_front/day.jpg"
image school day = "bg/school_front/day.jpg"
image school day rain = "bg/school_front/rain.jpg"
image school evening = "bg/school_front/evening.jpg"
image school night dark = "bg/school_front/night_dark.jpg"
image school night dark rain = "bg/school_front/night_dark_rain.jpg"
image school night light = "bg/school_front/night_light.jpg"
image school night light rain = "bg/school_front/night_light_rain.jpg"
image school cloudy = "bg/school_front/cloud.jpg"

image classroom = "bg/classroom/day.jpg"
image classroom day = "bg/classroom/day.jpg"
image classroom cloudy = "bg/classroom/cloud.jpg"
image classroom evening = "bg/classroom/evening.jpg"
image classroom night dark = "bg/classroom/night_dark.jpg"
image classroom night light = "bg/classroom/night_light.jpg"
image classroom night dark rain = "bg/classroom/night_dark_rain.jpg"
image classroom night light rain = "bg/classroom/night_light_rain.jpg"

image hallway = "bg/hallway/day.jpg"
image hallway day = "bg/hallway/day.jpg"
image hallway day rain = "bg/hallway/rain.jpg"
image hallway cloudy = "bg/hallway/cloud.jpg"
image hallway evening = "bg/hallway/evening.jpg"
image hallway night dark = "bg/hallway/night_dark.jpg"
image hallway night light = "bg/hallway/night_light.jpg"

image hallway alt = "bg/other_hallway/day.jpg"
image hallway alt day = "bg/other_hallway/day.jpg"
image hallway alt cloudy = "bg/other_hallway/cloud.jpg"
image hallway alt evening = "bg/other_hallway/evening.jpg"
image hallway alt night dark = "bg/other_hallway/night_dark.jpg"
image hallway alt night light = "bg/other_hallway/night_light.jpg"

image auditorium = "bg/auditorium/day.jpg"
image auditorium day = "bg/auditorium/day.jpg"
image auditorium cloudy = "bg/auditorium/cloud.jpg"
image auditorium evening = "bg/auditorium/evening.jpg"
image auditorium night dark = "bg/auditorium/night_dark.jpg"
image auditorium night light = "bg/auditorium/night_light.jpg"

image library = "bg/library.jpg"

image home = "bg/home/day.jpg"
image home day = "bg/home/day.jpg"
image home cloudy = "bg/home/cloud.jpg"
image home evening = "bg/home/evening.jpg"
image home night dark = "bg/home/night_dark.jpg"
image home night light = "bg/home/night_light.jpg"

image bedroom = "bg/bedroom/day.jpg"
image bedroom day = "bg/bedroom/day.jpg"
image bedroom cloudy = "bg/bedroom/cloud.jpg"
image bedroom evening = "bg/bedroom/evening.jpg"
image bedroom night dark = "bg/bedroom/night_dark.jpg"
image bedroom night light = "bg/bedroom/night_light.jpg"

image konbini = "bg/konbini.jpg"
image art_store = "bg/art_store.jpg"

image black = Solid('#000')
